security:
  basic:
    enabled: false
  require-ssl: ${requireSsl:true}
  jwt:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-store-oauth-key: ${keystoreOAuthKey}
    key-store-saml-key: ${keystoreSAMLKey}
  saml:
    idp:
      metadata-location: ${samlIdpMetadataLocation}
      provider: ${samlAuthnRequestProviderName:}
      entity-id: ${samlAuthnRequestEntityId}
      auth-contexts: ${samlAuthnContexts:}
      passive: ${samlPassive:false}
      force-auth: ${samlForceAuth:false}
    endpoint:
      base: ${samlBaseEndpoint:/saml}
      login: ${samlLoginEndpoint:/login}
      logout: ${samlLogoutEndpoint:/logout}
      single-logout: ${samlSingleLogoutEndpoint:/singlelogout}
      sso: ${samlSSOEndpoint:/sso}
      sso-hok: ${samlSSOHOKEndpoint:/ssohok}
      metadata: ${samlMetadataEndpoint:/metadata}
    attribute-names:
      group: ${samlGroupAttributeNames:http://schemas.xmlsoap.org/claims/Group}
      email: ${samlEmailAttributeNames:http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress}
      username: ${samlUsernameAttributeNames:http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname}
    include-groups: 
    logging:
      messages: false
      errors: true

server:
  port: ${serverPort:8443}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}
  implementation:
    port: ${waterAuthUrlServerPort:443}
    server: ${waterAuthUrlServerName:}
    context: ${waterAuthUrlContextPath:/}
  routing:
    login-success: ${loginSuccessTargetUrl:/}
    login-error: ${loginErrorTargetUrl:/auth-error}
    logout-success: ${logoutSuccessTargetUrl:/out}

spring:
  session:
    jdbc:
      initializer:
        enabled: ${dbInitializerEnabled:true}
  datasource:
    url: ${dbConnectionUrl}
    username: ${dbUsername}
    password: ${dbPassword}

logging:
  level:
    org:
      springframework: ${springFrameworkLogLevel:info}
